name: Auto Update
on:
  workflow_dispatch:

jobs:
  auto-update:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '>=1.23.2'

      - name: Clone MWAUpdater
        run: git clone https://github.com/TeamYukizome/MWAUpdater.git
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Run auto-update script
        run: cd MWAUpdater && go run .